// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: pb/discover.proto

package discoverservicepb

import (
	_ "github.com/grpc-ecosystem/grpc-gateway/v2/protoc-gen-openapiv2/options"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	anypb "google.golang.org/protobuf/types/known/anypb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Response struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NewContent    string                 `protobuf:"bytes,1,opt,name=newContent,proto3" json:"newContent,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Response) Reset() {
	*x = Response{}
	mi := &file_pb_discover_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Response) ProtoMessage() {}

func (x *Response) ProtoReflect() protoreflect.Message {
	mi := &file_pb_discover_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Response.ProtoReflect.Descriptor instead.
func (*Response) Descriptor() ([]byte, []int) {
	return file_pb_discover_proto_rawDescGZIP(), []int{0}
}

func (x *Response) GetNewContent() string {
	if x != nil {
		return x.NewContent
	}
	return ""
}

type GetParamInBodyRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Content       string                 `protobuf:"bytes,2,opt,name=content,proto3" json:"content,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetParamInBodyRequest) Reset() {
	*x = GetParamInBodyRequest{}
	mi := &file_pb_discover_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetParamInBodyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetParamInBodyRequest) ProtoMessage() {}

func (x *GetParamInBodyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pb_discover_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetParamInBodyRequest.ProtoReflect.Descriptor instead.
func (*GetParamInBodyRequest) Descriptor() ([]byte, []int) {
	return file_pb_discover_proto_rawDescGZIP(), []int{1}
}

func (x *GetParamInBodyRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *GetParamInBodyRequest) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

type GetParamInHeaderRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Content       string                 `protobuf:"bytes,2,opt,name=content,proto3" json:"content,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetParamInHeaderRequest) Reset() {
	*x = GetParamInHeaderRequest{}
	mi := &file_pb_discover_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetParamInHeaderRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetParamInHeaderRequest) ProtoMessage() {}

func (x *GetParamInHeaderRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pb_discover_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetParamInHeaderRequest.ProtoReflect.Descriptor instead.
func (*GetParamInHeaderRequest) Descriptor() ([]byte, []int) {
	return file_pb_discover_proto_rawDescGZIP(), []int{2}
}

func (x *GetParamInHeaderRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *GetParamInHeaderRequest) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

type PostUnstructuredDataRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Data          *anypb.Any             `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PostUnstructuredDataRequest) Reset() {
	*x = PostUnstructuredDataRequest{}
	mi := &file_pb_discover_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PostUnstructuredDataRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PostUnstructuredDataRequest) ProtoMessage() {}

func (x *PostUnstructuredDataRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pb_discover_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PostUnstructuredDataRequest.ProtoReflect.Descriptor instead.
func (*PostUnstructuredDataRequest) Descriptor() ([]byte, []int) {
	return file_pb_discover_proto_rawDescGZIP(), []int{3}
}

func (x *PostUnstructuredDataRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *PostUnstructuredDataRequest) GetData() *anypb.Any {
	if x != nil {
		return x.Data
	}
	return nil
}

type PostUnstructuredDataResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Data          *anypb.Any             `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PostUnstructuredDataResponse) Reset() {
	*x = PostUnstructuredDataResponse{}
	mi := &file_pb_discover_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PostUnstructuredDataResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PostUnstructuredDataResponse) ProtoMessage() {}

func (x *PostUnstructuredDataResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pb_discover_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PostUnstructuredDataResponse.ProtoReflect.Descriptor instead.
func (*PostUnstructuredDataResponse) Descriptor() ([]byte, []int) {
	return file_pb_discover_proto_rawDescGZIP(), []int{4}
}

func (x *PostUnstructuredDataResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *PostUnstructuredDataResponse) GetData() *anypb.Any {
	if x != nil {
		return x.Data
	}
	return nil
}

var File_pb_discover_proto protoreflect.FileDescriptor

const file_pb_discover_proto_rawDesc = "" +
	"\n" +
	"\x11pb/discover.proto\x12\x11discoverservicepb\x1a\x1cgoogle/api/annotations.proto\x1a\x19google/protobuf/any.proto\x1a.protoc-gen-openapiv2/options/annotations.proto\"*\n" +
	"\bResponse\x12\x1e\n" +
	"\n" +
	"newContent\x18\x01 \x01(\tR\n" +
	"newContent\"\x87\x01\n" +
	"\x15GetParamInBodyRequest\x126\n" +
	"\x02id\x18\x01 \x01(\tB&\x92A#2!Unique identifier for the requestR\x02id\x126\n" +
	"\acontent\x18\x02 \x01(\tB\x1c\x92A\x192\x17Content to be processedR\acontent\"\x89\x01\n" +
	"\x17GetParamInHeaderRequest\x126\n" +
	"\x02id\x18\x01 \x01(\tB&\x92A#2!Unique identifier for the requestR\x02id\x126\n" +
	"\acontent\x18\x02 \x01(\tB\x1c\x92A\x192\x17Content to be processedR\acontent\"\xa1\x01\n" +
	"\x1bPostUnstructuredDataRequest\x123\n" +
	"\x02id\x18\x01 \x01(\tB#\x92A 2\x1eUnique identifier for the dataR\x02id\x12M\n" +
	"\x04data\x18\x02 \x01(\v2\x14.google.protobuf.AnyB#\x92A 2\x1eUnstructured data to be postedR\x04data\"\x95\x01\n" +
	"\x1cPostUnstructuredDataResponse\x127\n" +
	"\x02id\x18\x01 \x01(\tB'\x92A$2\"Unique identifier for the responseR\x02id\x12<\n" +
	"\x04data\x18\x02 \x01(\v2\x14.google.protobuf.AnyB\x12\x92A\x0f2\rResponse dataR\x04data2\xb8\x05\n" +
	"\x0fDiscoverService\x12\xd8\x01\n" +
	"\x0eGetParamInBody\x12(.discoverservicepb.GetParamInBodyRequest\x1a\x1b.discoverservicepb.Response\"\x7f\x92AZ\n" +
	"\n" +
	"Parameters\x12\x15Get parameter in body\x1a5Retrieves parameter information from the request body\x82\xd3\xe4\x93\x02\x1c\x12\x1a/v1/get-param-in-body/{id}\x12\xdf\x01\n" +
	"\x10GetParamInHeader\x12*.discoverservicepb.GetParamInHeaderRequest\x1a\x1b.discoverservicepb.Response\"\x81\x01\x92A_\n" +
	"\n" +
	"Parameters\x12\x17Get parameter in header\x1a8Retrieves parameter information from the request headers\x82\xd3\xe4\x93\x02\x19\x12\x17/v1/get-param-in-header\x12\xe7\x01\n" +
	"\x14PostUnstructuredData\x12..discoverservicepb.PostUnstructuredDataRequest\x1a/.discoverservicepb.PostUnstructuredDataResponse\"n\x92AF\n" +
	"\x04Data\x12\x16Post unstructured data\x1a&Posts unstructured data to the service\x82\xd3\xe4\x93\x02\x1f:\x01*\"\x1a/v1/post/unstructured-dataB\xaf\x01\x92A\x97\x01\x12m\n" +
	"\x14Discover Service API\x12#API for discover service operations\"+\n" +
	"\vAPI Support\x12\x1chttps://github.com/your-repo2\x031.0*\x02\x01\x022\x10application/json:\x10application/jsonZ\x12/discoverservicepbb\x06proto3"

var (
	file_pb_discover_proto_rawDescOnce sync.Once
	file_pb_discover_proto_rawDescData []byte
)

func file_pb_discover_proto_rawDescGZIP() []byte {
	file_pb_discover_proto_rawDescOnce.Do(func() {
		file_pb_discover_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pb_discover_proto_rawDesc), len(file_pb_discover_proto_rawDesc)))
	})
	return file_pb_discover_proto_rawDescData
}

var file_pb_discover_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_pb_discover_proto_goTypes = []any{
	(*Response)(nil),                     // 0: discoverservicepb.Response
	(*GetParamInBodyRequest)(nil),        // 1: discoverservicepb.GetParamInBodyRequest
	(*GetParamInHeaderRequest)(nil),      // 2: discoverservicepb.GetParamInHeaderRequest
	(*PostUnstructuredDataRequest)(nil),  // 3: discoverservicepb.PostUnstructuredDataRequest
	(*PostUnstructuredDataResponse)(nil), // 4: discoverservicepb.PostUnstructuredDataResponse
	(*anypb.Any)(nil),                    // 5: google.protobuf.Any
}
var file_pb_discover_proto_depIdxs = []int32{
	5, // 0: discoverservicepb.PostUnstructuredDataRequest.data:type_name -> google.protobuf.Any
	5, // 1: discoverservicepb.PostUnstructuredDataResponse.data:type_name -> google.protobuf.Any
	1, // 2: discoverservicepb.DiscoverService.GetParamInBody:input_type -> discoverservicepb.GetParamInBodyRequest
	2, // 3: discoverservicepb.DiscoverService.GetParamInHeader:input_type -> discoverservicepb.GetParamInHeaderRequest
	3, // 4: discoverservicepb.DiscoverService.PostUnstructuredData:input_type -> discoverservicepb.PostUnstructuredDataRequest
	0, // 5: discoverservicepb.DiscoverService.GetParamInBody:output_type -> discoverservicepb.Response
	0, // 6: discoverservicepb.DiscoverService.GetParamInHeader:output_type -> discoverservicepb.Response
	4, // 7: discoverservicepb.DiscoverService.PostUnstructuredData:output_type -> discoverservicepb.PostUnstructuredDataResponse
	5, // [5:8] is the sub-list for method output_type
	2, // [2:5] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_pb_discover_proto_init() }
func file_pb_discover_proto_init() {
	if File_pb_discover_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pb_discover_proto_rawDesc), len(file_pb_discover_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_pb_discover_proto_goTypes,
		DependencyIndexes: file_pb_discover_proto_depIdxs,
		MessageInfos:      file_pb_discover_proto_msgTypes,
	}.Build()
	File_pb_discover_proto = out.File
	file_pb_discover_proto_goTypes = nil
	file_pb_discover_proto_depIdxs = nil
}
